opendatahub-io/ai-edge

Makefile
README.md
acm/odh-edge/acm-observability/files/uwm_metrics.yaml
acm/odh-edge/acm-observability/kustomization.yaml
acm/odh-edge/acm-observability/namespace.yaml

- To pull metrics from the edge model namespace we need to add a configmap defining those metrics.
- Once this CM is created in the namespace then the metrics are collected and pushed back to the hub cluster.
- Add instructions in README to setup observability

add uwm allow list cm for model namespace

---

acm/odh-edge/acm-observability/files/uwm_metrics.yaml

Add OVMS metrics to UWM list

---

acm/odh-edge/acm-observability/kustomization.yaml
acm/odh-edge/acm-observability/model-servicemonitor.yaml
acm/odh-edge/acm-observability/namespace.yaml

Add kustomize file for model serviceMonitor. The specifics of namespace and app label may have to be changed once the pipeline is in place.

add servicemonitor for model metrics

---

acm/odh-edge/acm-observability/model-servicemonitor.yaml

The name of the Service Monitor should be lowercase

edit servicemonitor name to lowercase

---

README.md
acm/odh-edge/base/model-servicemonitor.yaml
pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml

- Edit readme since those steps are now automated through the acm app
- Add a step in the pipeline to create the metrics service 
- Add the /metrics path to the servicemonitor

add metrics service to model creation and add path to servicemonitor

---

acm/odh-edge/apps/bike-rental-app/kustomization.yaml
acm/odh-edge/apps/tensorflow-housing-app/kustomization.yaml
acm/odh-edge/base/kustomization.yaml
acm/odh-edge/base/model-deployment.yaml
acm/odh-edge/base/model-route.yaml
acm/odh-edge/base/model-service.yaml

Adds kustomized Deployment, Service, and Route for each model.
I've only used kustomize locally to check the contents, but will deploy to Gitea now

Deploy models to edge clusters

---

README.md

Make sure lines are not joined together per guidance in https://github.com/opendatahub-io/ai-edge/issues/81#issuecomment-1724745570..
Fixes https://github.com/opendatahub-io/ai-edge/issues/81.
I looked at https://github.com/adelton/opendatahub-ai-edge/tree/issue-81.

Make sure lines are not joined together.

---

pipelines/README.md

Primarily the trained models live in this repository.
I looked at https://github.com/adelton/opendatahub-ai-edge/blob/this-repository/pipelines/README.md.

Primarily the trained models live in this repository.

---

pipelines/README.md
pipelines/tekton/azureml-container-pipeline/aws-env.yaml

Make it clearer where to update the S3 bucket name.
I checked https://github.com/adelton/opendatahub-ai-edge/blob/bucket-name/pipelines/README.md.

Make it clearer where to update the S3 bucket name.

---

.gitignore
pipelines/README.md

Make it clear that the S3 bucket needs to be created and filled.
Checked https://github.com/adelton/opendatahub-ai-edge/blob/s3-bucket/pipelines/README.md.

Make it clear that the S3 bucket needs to be created and filled.

---

pipelines/README.md

Describe the expected result of the container-building pipeline(s).
Checked https://github.com/adelton/opendatahub-ai-edge/blob/build-check-result/pipelines/README.md.

Describe the expected result of the container-building pipeline(s).

---

README.md

Clarify the objectives of the PoC.
Looked at https://github.com/adelton/opendatahub-ai-edge/tree/objective.

Clarify the objectives of the PoC.

---

pipelines/tekton/azureml-container-pipeline/azureml-container-pipelinerun-bike-rentals.yaml
pipelines/tekton/azureml-container-pipeline/azureml-container-pipelinerun-tensorflow-housing.yaml

For the container build, just use the upstream repo.
For the GitOps later, we might prescribe to use a clone. But for now it's better to point to the up-to-date upstream than the stale gitea content.
Fixes https://github.com/opendatahub-io/ai-edge/issues/103.
Manually.

For the container build, just use the upstream repo.

---

README.md

Add presumably missing word and space.
Looked at https://github.com/adelton/opendatahub-ai-edge/tree/small-typos.

Add presumably missing word and space.

---

pipelines/tekton/gitops-update-pipeline/kustomization.yaml

Previously official Tekton Task was broken when using Gitea but now it's fixed.
Resolves #67

Use official Tekton `github-open-pr` task

---

pipelines/README.md

The ultimate result of the build pipeline is the container image.
Looked at https://github.com/adelton/opendatahub-ai-edge/tree/dockerImageReference/pipelines.

The ultimate result of the build pipeline is the container image.

---

pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-rest-svc-task.yaml

Use the UBI image from the unauthenticated registry.
```bash
oc apply -f tekton/test-mlflow-image-pipeline/test-mlflow-rest-svc-task.yaml
oc create -f tekton/test-mlflow-image-pipeline/test-mlflow-image-pipelinerun-tensorflow-housing.yaml
```

Use the UBI image from the unauthenticated registry.

---

pipelines/models/tensorflow-housing/README.md

Document where the `tensorflow-housing` model came from, and how to regenerate the model.
Running `mlflow run` produces the same directory structure. I did not check if it produces exactly the same model.

How was this model generated?

---

pipelines/README.md

Expand description and results of the test pipeline.
Looked at https://github.com/adelton/opendatahub-ai-edge/tree/test-pipeline/pipelines.

Expand description and results of the test pipeline.

---

DEVELOPMENT.md
Makefile
README.md
test/acm/bike-rental-app/kustomization.yaml
test/acm/tensorflow-housing-app/kustomization.yaml
test/gitops/bike-rental-app/kustomization.yaml
test/gitops/tensorflow-housing-app/kustomization.yaml

This adds a `make` recipe that can be used to deploy an isolated custom version of one of the apps from a custom Git branch to a custom namespace. The intention is to replace the cumbersome manual, error-prone way that we currently do this.
This has been tested by following the instructions that have been added to the README.md in this PR.

Add Make recipe to allow for easier testing of changes

---

pipelines/README.md
pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml

Clean up after the setup, delete the deployment at the end of test.
Allow using `upon-end` Pipeline parameter to `stop` or `keep`, apart from the default `delete`.
Based on information in https://github.com/opendatahub-io/ai-edge/pull/119#issuecomment-1749253767.
Manually.

Delete the deployment at the end of test, allow using upon-end parameter to "stop" or "keep".

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/user-story.md

Add issue templates so there's a bit more consistency and structure in the repo.

Add issue templates

---

pipelines/README.md
pipelines/tekton/gitops-update-pipeline/example-pipelineruns/example-git-credentials-secret.yaml
pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-bike-rentals.yaml
pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-tensorflow-housing.yaml
pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml

Expand description of the GitOps pipeline, update defaults to GitHub.
Fixes https://github.com/opendatahub-io/ai-edge/issues/90.
I tested in my fork in GitHub until I got the pull request properly filed.

Expand description of the GitOps pipeline, update defaults to GitHub.

---

README.md

Clarify the introduction to the repository.
Not tested.

Clarify the introduction to the repository.

---

README.md

Order components based on their usage, losen version requirements, add information about accounts on hosted services.
Note tested.

Order components based on their usage, losen version requirements.

---

README.md

Clarify that Gitea is optional.
Not tested.

Clarify that Gitea is optional.

---

acm/odh-edge/apps/bike-rental-app/kustomization.yaml
acm/odh-edge/apps/tensorflow-housing-app/kustomization.yaml

Use digests of newest images in https://quay.io/organization/rhoai-edge repositories.
Not tested, just copied the SHA-256's from quay WebUI.

Use digests of newest images in quay.io/rhoai-edge/ repositories.

---

pipelines/README.md

Clarify what is admin needed for in pipelines.
Visually.

Clarify what is admin needed for in pipelines.

---

README.md
acm/registration/near-edge/base/near-edge.yaml

Restructure the top-level README to make the order of steps clearer.
Fixes https://github.com/opendatahub-io/ai-edge/issues/97.
Fixes https://github.com/opendatahub-io/ai-edge/issues/96.
Not tested.

Restructure the top-level README to make the order of steps clearer.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/user-story.md

The new templates are a bit hard to read when a lot of text is used, so I switched the section styling to headings.
| New| Old |
| ---- | ----- |
| ![image](https://github.com/opendatahub-io/ai-edge/assets/99439005/1322e290-9ed3-480b-8442-7dd3849f8a71) | ![image](https://github.com/opendatahub-io/ai-edge/assets/99439005/72739621-1b48-4c26-bd56-6213902634eb) |
Eyes 👀.

Improve issues readability

---

OWNERS

Moving me from just reviewers to approvers and also including @apodhrad.
We believe I and also @apodhrad should be included into the approver list, not just reviewer list.
N/A

Include MarianMacik and apodhrad as approvers

---

README.md
acm/odh-core/acm-observability/files/metrics_list.yaml
acm/odh-core/acm-observability/kustomization.yaml

The metrics list CM should be created on the Core/hub cluster.

Create Metrics CM in correct place  on core cluster

---

README.md

Properly close the verbatim block.

---

pipelines/README.md

I followed https://github.com/opendatahub-io/ai-edge/blob/main/pipelines/README.md#for-git-fetch but by only changing `fetch-model` value to `git`, I got
```
ls: cannot access 'model_dir-bike-rentals-auto-ml/bike-rentals-auto-ml/': No such file or directory
```
It seems `modelRelativePath` also needs to be set, and the `aiedge-e2e.tensorflow-housing.pipelinerun.yaml` is already tailored to demonstrate the git fetch approach.
Manually.

The PipelineRun YAML where git fetch approach work out of box is the tensorflow housing one.

---

README.md
acm/odh-edge/base/namespace.yaml
acm/registration/near-edge/base/near-edge.yaml
acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml
acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
byo-mgmt/registration/near-edge/base/argocd-application.yaml
byo-mgmt/registration/near-edge/base/kustomization.yaml
byo-mgmt/registration/near-edge/overlays/bike-rental-app/kustomization.yaml
byo-mgmt/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
docs/byo-mgmt-gitops.md
docs/preparing_the_infrastructure.md

JIRA: https://issues.redhat.com/browse/RHOAIENG-2787
This PR stacks upon #229, and the commits here may change slightly, if there are changes required for that.
We love OCM/ACM and recommend using it where possible, but if you've got your own multi-cluster and application management solution, and don't want to have to replace it to use the solutions in this repo, then you can instead use this as a starting point to integrate it yourself.
The steps are intended to be documented in such a way that they could be either executed manually or adapted to fit into any system.

RHOAIENG-2787: Example of GitOps approach with ArgoCD directly, without ACM

---

docs/byo-mgmt-gitops.md

Fix link to the metrics_list.yaml.
Manually.

Fix link to the metrics_list.yaml.

---

pipelines/README.md

The PipelineRuns are in separate files.
The original command did not work.

The PipelineRuns are in separate files.

---

pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml

What the Task builds is actually an image, not a container.
Not tested.

What the Task builds is actually an image, not a container.

---

pipelines/tekton/aiedge-e2e/tasks/kserve-download-model.yaml

This update may be required to support self signed certificate support for S3 servers
- Use the e2e test provided in the repo
- Run 
```bash
make AWS_SECRET_ACCESS_KEY=... AWS_ACCESS_KEY_ID=... S3_REGION=... S3_ENDPOINT=... IMAGE_REGISTRY_USERNAME=...  IMAGE_REGISTRY_PASSWORD=... S3_BUCKET=... NAMESPACE=... TARGET_IMAGE_TAGS_JSON=... go-test-setup
```
- And then run 
```bash
make AWS_SECRET_ACCESS_KEY=... AWS_ACCESS_KEY_ID=... S3_REGION=... S3_ENDPOINT=... IMAGE_REGISTRY_USERNAME=...  IMAGE_REGISTRY_PASSWORD=...  S3_BUCKET=... NAMESPACE=... TARGET_IMAGE_TAGS_JSON=... go-test
```

RHOAIENG-4549 Update the kserve-model-downloader to version v0.11.1.3

---

acm/odh-edge/apps/bike-rental-app/kustomization.yaml
acm/odh-edge/apps/tensorflow-housing-app/kustomization.yaml
acm/odh-edge/base/model-deployment.yaml
pipelines/tekton/aiedge-e2e/aiedge-e2e.bike-rentals.pipelinerun.yaml
pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml
pipelines/tekton/aiedge-e2e/aiedge-e2e.tensorflow-housing.pipelinerun.yaml
pipelines/tekton/aiedge-e2e/test-data/bike-rentals-test-data-cm.yaml
pipelines/tekton/aiedge-e2e/test-data/tensorflow-housing-test-data-cm.yaml

This PR is a simple one to include model-name as label to the pipelineruns helping in filtering the pipelineruns based on labels and also attach model-name as part of generateName to distinguish the pipelineruns name.
- You can create a new pipelinerun to see the change in name of the pipelinerun
- You can run below command to filter the pipelineruns based on the label
`oc get pipelineruns -l model-name=bike-rentals-auto-ml`

RHOAIENG-436: Add model-name to labels and generateName

---

test/e2e-tests/README.md

Removes a line that was pasted by mistake in a code block in the e2e tests README.

Remove unnecessary line in a code block in e2e tests README

---

README.md
acm/odh-edge/apps/telemetry/namespace.yaml
acm/odh-edge/base/namespace.yaml
docs/byo-mgmt-gitops.md
docs/preparing_the_infrastructure.md

Fix the spelling of Argo CD per https://github.com/argoproj/argo-cd.
No testing was done.

Fix the spelling of Argo CD per https://github.com/argoproj/argo-cd.

---

pipelines/tekton/aiedge-e2e/tasks/test-model-rest-svc-task.yaml
pipelines/tekton/aiedge-e2e/test-data/tensorflow-housing-test-data-cm.yaml

Test the full expected output value. For the given `data.json` input, the model should give deterministic output and we already have the value in `output.json`.
Manually, the
```
$ oc apply -k tekton/aiedge-e2e/
$ oc create -f tekton/aiedge-e2e/aiedge-e2e.tensorflow-housing.pipelinerun.yaml
$ oc create -f tekton/aiedge-e2e/aiedge-e2e.bike-rentals.pipelinerun.yaml
```
steps pass.

Test the full expected output value.

---

acm/odh-edge/apps/bike-rental-app/bike-rental-inference-generator-cronjob.yaml

Reading the comments lead to a false understanding of the code. Make the comments closer to matching the observable behaviour.
Manually, by reruning the bash snippets and staring at the results.

Fix the comment to match the actual arithmetic.

---

README.md

Capitalize Red Hat Build of OpenTelemetry correctly based on what it is called in the OperatorHub.
Not tested.

Capitalize Red Hat Build of OpenTelemetry correctly.

---

cli/pkg/commands/common/cmd.go
cli/pkg/commands/images/build.go
cli/pkg/commands/images/images.go
cli/pkg/commands/images/update.go
cli/pkg/commands/models/add.go
cli/pkg/commands/models/models.go
cli/pkg/commands/root.go
cli/pkg/edgeclient/client.go

One of the common conventions in Go is to [group imports into several groups](https://google.github.io/styleguide/go/decisions.html#import-grouping), the most widely adopted is to group them into
```
standard library packages
third-party packages
project packages
```
None

Organize go imports by following grouping convention

---

Makefile
docs/cli.md

Use the oc CLI tool to match the rest of the repo documentation.
Manually.

Use the oc CLI tool to match the rest of the repo documentation.

---

README.md

Match the order of the core cluster and edge clusters from the preceding sections.
Not tested.

Match the order of the core cluster and edge clusters from the preceding sections.

---

test/e2e-tests/support/kustomize.go

Config maps were trying to be created more then once 
- Run e2e tests with no tests enabled
- `bike-rentals-test-data` config map should be created
- Run e2e tests with no tests enabled and there should be no error

fix: config maps can now be used in setup if they already exist

---

test/e2e-tests/README.md

Updates the e2e README to reflect changes in the structure for the `config.json` in the e2e tests
- N/A

Update e2e README to show new organised fields

---

README.md
docs/glossary.md

JIRA: [RHOAIENG-205](https://issues.redhat.com/browse/RHOAIENG-205)
Adding a glossary for stand terms. This is just the first set. We plan to iteratively update this terminology list. Ref: https://github.com/LaVLaS/ai-edge/blob/glossary/docs/glossary.md
I did move the doc that Landon had started but do we want to add more terminology to this? 
N/A

RHOAIENG-205-Define the standard terms

---

test/shell-pipeline-tests/seldon-bike-rentals/pipelines-test-seldon-bike-rentals.sh

Just a timeout increase as pipeline is completing in 217-220 retries, sometimes failing because of not enough waiting time.
Periodic job.

Increase timeout for the s3-fetch pipeline with bike-rentals
