opendatahub-io/ai-edge

README.md, acm/registration/kustomization.yaml, acm/registration/near-edge/base/kustomization.yaml, acm/registration/near-edge/base/near-edge.yaml, acm/registration/near-edge/kustomization.yaml, acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml, acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
It seems like all resources get created in a namespace on the target clusters with the same name as the namespace that the subscription on the hub cluster is created in, despite the resources explicitly having a different namespace set.
This change adds new subscriptions such that the two model apps get created in different namespaces on the target clusters.
This change is currently rolled out to the ACM cluster, using `oc apply -k acm/registration`, and the synchronization has been successful, and the resources can be seen created on the target clusters.
=> Use ACM app per app to ensure correct NS placement

pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml
Everybody who is using the pipeline code for dev purposes keeps pushing to the `:1` tag on Quay and breaking other people's code. This change pushes the image to a unique tag to avoid that.
Resolves #64
=> Make skopeo push to unique tag

pipelines/README.md
The "a repository" suggests that the repository name does not matter, that it will get configured later.
However, the next steps allow for configuration of the Quay namespace via the `target-imagerepo` parameter, but not the repository name. Incidently, `target-imagerepo` is not a good name for a target namespace.
After I renamed the repository to `tensorflow-housing`, the `skopeo-copy` task stopped failing.
=> The Quay repository has to have specific name.

Makefile, README.md
Update the  existing Observability setup instructions to add some minor context to the steps for enabling UserWorkloadMonitoring.
Deployed manually to a new cluster
No errors introduced
=> Clarify edge UWM info in the README

README.md, acm/odh-core/olm-operator-subscriptions/opendatahub-operator.yaml
Updates the ODH Operator subscription to use the `fast` channel for v2.x installations of ODH.  Additionally adds the `DataScienceCluster` installation to deploy ODH in the cluster
Closes #60
Local deployment into my test cluster
=> Move the ODH Operator subscription to the fast channel for the v2.x release of ODH

pipelines/tekton/azureml-container-pipeline/aws-env.yaml
The bucket name does not seem to be needed in aws-storage-config, it is specified as aws-bucket-name parameter in PipelineRuns.
Tested manually.
=> The bucket name does not seem to be needed in aws-storage-config.

README.md, acm/odh-core/olm-operator-subscriptions/gitea/catalogsource.yaml, acm/odh-core/olm-operator-subscriptions/gitea/kustomization.yaml, acm/odh-core/olm-operator-subscriptions/gitea/namespace.yaml, acm/odh-core/olm-operator-subscriptions/gitea/operatorgroup.yaml, acm/odh-core/olm-operator-subscriptions/gitea/subscription.yaml, acm/odh-core/olm-operator-subscriptions/kustomization.yaml
Adds support for deploying a Gitea server in the cluster to enable a target for the gitops workflow
Closes #28
Deployed and testing the in demo cluster
Manifest successfully deploys the gitea-operator which also deploy a gitea-server application
=> Add manifest files for deploying the gitea-operator

pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml
The metrics service is not used in the test-mlflow-image-pipeline in any way, based on information in https://github.com/opendatahub-io/ai-edge/pull/119#issuecomment-1749253767.
Tested manually.
=> The metrics service is not used in the test-mlflow-image-pipeline in any way.

acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml, acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
The gitea-ai-edge-rhoai-edge-acm repo has image digests that do not exist on quay. So out of box, applications created with
```
oc apply -k acm/registration/
```
crash because they cannot get the container from quay.
Manually.
=> The gitea-ai-edge-rhoai-edge-acm repo has image digests that do not exist on quay.

pipelines/README.md, pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-bike-rentals.yaml, pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-tensorflow-housing.yaml, pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml, pipelines/tekton/gitops-update-pipeline/kustomization.yaml, pipelines/tekton/gitops-update-pipeline/test-mlflow-retrieve-image-info-task.yaml, pipelines/tekton/test-mlflow-image-pipeline/kustomization.yaml, pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml, pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipelinerun-bike-rental.yaml, pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipelinerun-tensorflow-housing.yaml, pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-record-image-task.yaml
File the pull request with information about the latest built and pushed image for the model retrieved from the PipelineRuns.
Fixes https://github.com/opendatahub-io/ai-edge/issues/92.
Fixes https://github.com/opendatahub-io/ai-edge/issues/125.
This builds on top of https://github.com/opendatahub-io/ai-edge/pull/123.
Manually.
=> File the pull request with information about the latest built and pushed image for the model

README.md, acm/odh-core/olm-operator-subscriptions/kustomization.yaml, gitea/README.md, gitea/operator/catalogsource.yaml, gitea/operator/kustomization.yaml, gitea/operator/namespace.yaml, gitea/operator/operatorgroup.yaml, gitea/operator/subscription.yaml, gitea/server/gitea.yaml, gitea/server/kustomization.yaml
Move the gitea info and manifests to a gitea repo as an optional component that users can deploy manually for there use case
Closes #129 
Closes #116
Manually deployment to ensure the gitea kustomize manifests parse and apply successfully
Info is  accurate and easy to understand
=> Move gitea manifest out of the odh-core ACM Application

acm/registration/near-edge/base/kustomization.yaml, acm/registration/near-edge/base/nameReference.yaml, acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml, acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
Add support for git credentials for ACM Subscriptions.
Since the GitOps pipeline can file pull requests with container image changes in authenticated git repositories, ACM should be able to deploy applications from those repositories as well.
I tested that a different access token can be used (only for reading).
Manually.
=> Add support for git credentials for ACM Subscriptions.

OWNERS
Add an OWNERS file that is required for the onboarding to [Prow](https://github.com/openshift/release) and enabling the [tide](https://docs.prow.k8s.io/docs/components/core/tide/pr-authors/) plugin
N/A
=> Add OWNERS file to the repo

Makefile
Added a dummy Makefile test target to allow onboarding to openshift-ci. Related to https://github.com/opendatahub-io/ai-edge/issues/166.
Run `make test`, the expected message is printed out.
=> Add a dummy Makefile test target

acm/registration/near-edge/base/near-edge.yaml
> In some unstable network scenarios, the managed clusters might be temporarily placed in unavailable or unreachable state.
That sounds very relevant to our use cases.
See the following section of the ACM docs for more info:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/applications/managing-applications#tolerations-config
=> Tolerate unreachable clusters in Placement

pipelines/README.md, pipelines/tekton/build-container-image-pipeline/build-container-image-pipeline.yaml, pipelines/tekton/build-container-image-pipeline/build-container-image-pipelinerun-bike-rentals.yaml, pipelines/tekton/build-container-image-pipeline/build-container-image-pipelinerun-tensorflow-housing.yaml, pipelines/tekton/build-container-image-pipeline/check-model-and-containerfile-exists.yaml, pipelines/tekton/build-container-image-pipeline/kserve-download-model.yaml
Fixes #57 
Added a git-clone task to clone the model repo from a git source. This addition required some model paths to be updated in multiple places.
Created a new pipeline run with the changes in my `srbiswas-pipeline-dev` project  and was able to have a successful pipeline run.
=> [RHOAIEDGE-15] Adding option to fetch from git

pipelines/tekton/build-container-image-pipeline/copy-model-from-pvc.yaml
The model-name parameter value needs to refer to a directory rather than a file, because it gets used later for the CONTEXT dir during the buildah build. Therefore, it needs to be copied recursively, using `cp -r`.
1. Try to use a single file in a PV as model-name in a pipeline run, and notice that it fails because the image build can't use it as the CONTEXT directory.
2. Upload a model directory to a PV using the Make target:
```
pushd pipelines/tekton/azureml-container-pipeline/model-upload
make NAME=bike-rentals-auto-ml \
MODEL_PATH=/var/home/gryan/src/github.com/opendatahub-io/ai-edge/pipelines/models/bike-rentals-auto-ml/  \
create
popd
```
3. Trigger a pipelinerun as follows:
```
cat << EOF | oc create -f -
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
generateName: …
```
=> Fix copy-model-from-pvc to allow dir upload

Makefile, pipelines/tekton/build-container-image-pipeline/aws-env.yaml, pipelines/tekton/build-container-image-pipeline/build-container-image-pipeline.yaml, pipelines/tekton/build-container-image-pipeline/build-container-image-pipelinerun-tensorflow-housing.yaml, test/shell-pipeline-tests/README.md, test/shell-pipeline-tests/common.sh, test/shell-pipeline-tests/openvino-bike-rentals/pipelines-test-openvino-bike-rentals.sh, test/shell-pipeline-tests/pipelines-test.sh, test/shell-pipeline-tests/tensorflow-housing/pipelines-test-tensorflow-housing.sh
…ops)
**JIRA:** [RHOAIENG-905](https://issues.redhat.com/browse/RHOAIENG-905)
Adds 2 scripts:
* common.sh which acts as a library
* pipeline-test.sh currently testing just the build-container-image-pipeline and test-mlflow-image-pipeline with housing (TensorFlow) version of the pipeline run
Locally using a separate cluster.
=> RHOAIENG-905 - Create a PR check for testing README file (without gitops)

DEVELOPMENT.md, Makefile, README.md, acm/registration/near-edge/base/near-edge.yaml, acm/registration/near-edge/kustomization.yaml, acm/registration/near-edge/openshift-gitops-gitopscluster.yaml, acm/registration/near-edge/openshift-gitops-managedclustersetbinding.yaml, acm/registration/near-edge/openshift-gitops-placement.yaml, acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml, acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml, acm/registration/near-edge/test/bike-rental-app/kustomization.yaml, acm/registration/near-edge/test/kustomization.yaml, acm/registration/near-edge/test/tensorflow-housing-app/kustomization.yaml, test/acm/bike-rental-app/kustomization.yaml, test/acm/tensorflow-housing-app/kustomization.yaml, test/gitops/bike-rental-app/kustomization.yaml
JIRA: https://issues.redhat.com/browse/RHOAIENG-203
This change moves the GitOps machinery from the ACM AppSubscription model that was used here before, to ACM's integration with the ArgoCD/OpenShift Pipelines pull controller. No changes are needed in the referenced gitops repositories.
I've added some kustomize tests to validate that all modifications occur as expected. These can be checked by witnessing that the following command exits with a return code of 0:
```
kustomize build acm/registration/near-edge/test/
```
I have also verified that both examples deploy as expected, and can be deleted as expected also. This can be done using the following command:
```
oc apply -k acm/registration/
```
and then once satisfied, deletion can be achieved using the following:
```
oc delete -k …
```
=> RHOAIENG-203: Use ArgoCD pull controller integration for GitOps

README.md, pipelines/tekton/aiedge-e2e/tasks/copy-model-from-pvc.yaml, pipelines/tekton/aiedge-e2e/tasks/kustomization.yaml
We are deprecating the `build-container-image-pipeline` and `test-mlflow-image-pipeline` and need to preserve the `copy-model-from-pvc` Task with the aiedge-e2e pipeline
Confirmed that `kustomize build pipelines/tekton/aiedge-e2e/tasks/` includes the new task in the output
There are no issues with the kustomize manifest that applies the tasks to the cluster
=> Add copy-model-from-pvc Task to aiedge-e2e directory

acm/registration/near-edge/base/near-edge.yaml
In the `ApplicationSet`, the name of the `ConfigMap` referenced in the cluster decision resource generator was incorrect so syncing of the applications was broken. 
This was tested by following the README on a rosa hub cluster and an OpenShift local edge cluster.
=> Fix the ApplicationSet clusterDefinition generator

.gitignore, DEVELOPMENT.md, Makefile
Adds support for passing Make variables via a local env var file instead of on the command line
Successfully ran `make` against `go-test` and `go-test-setup` without any variables on the CLI
CI runs and local `make` execution works without any issues
=> Makefile: Add support to include vars from local env var file

test/shell-pipeline-tests/common.sh
**JIRA:** [RHOAIENG-3233](https://issues.redhat.com/browse/RHOAIENG-3233)
A small enhancement to the #205 which adds an absolute timestamp to each event rather than time since the last occurrence.
Locally + PR check.
=> RHOAIENG-3233 - follow-up: Show absolute timestamps for events

pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml
**JIRA:** [RHOAIENG-3359](https://issues.redhat.com/browse/RHOAIENG-3359)
Switches buildah image to use `registry.redhat.io/ubi9/buildah:latest`.
PR check.
=> RHOAIENG-3359 - Switch rhel8 to ubi9 image in buildah task

Makefile, README.md, pipelines/README.md, pipelines/tekton/aiedge-e2e/aiedge-e2e.bike-rentals.pipelinerun.yaml, pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml, pipelines/tekton/aiedge-e2e/aiedge-e2e.tensorflow-housing.pipelinerun.yaml, pipelines/tekton/aiedge-e2e/tasks/retrieve-build-image-info.task.yaml, test/e2e-tests/README.md, test/e2e-tests/support/options.go, test/e2e-tests/tests/pipelines_test.go
JIRA: https://issues.redhat.com/browse/RHOAIENG-2758
Before this change, the image registry, image name, and image tag, were all hardcoded or generated by the pipeline, rather than customizable through parameters.
This change makes it possible to specify one or more targets as full image tag references.
Accepting more than just a single image tag target allows for both uniqueness and meaning. The simplest example scenario is where there's a primary tag that's unique, which has the model version and pipelinerun id; then a secondary tag with just the model version, which tracks the current blessed image for that model version. Quay (and possibly other registries) even has a UI feature for visualising that different tags actually point to the same manifest.
It's still possible to use other …
=> RHOAIENG-2758: Accept one or more target image tags as a param

pipelines/tekton/aiedge-e2e/aiedge-e2e.bike-rentals.pipelinerun.yaml, pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml, pipelines/tekton/aiedge-e2e/aiedge-e2e.tensorflow-housing.pipelinerun.yaml, test/shell-pipeline-tests/README.md, test/shell-pipeline-tests/common.sh, test/shell-pipeline-tests/openvino-tensorflow-housing/pipelines-test-openvino-tensorflow-housing.sh, test/shell-pipeline-tests/seldon-bike-rentals/pipelines-test-seldon-bike-rentals.sh
**JIRAs:**
* [RHOAIENG-3368](https://issues.redhat.com/browse/RHOAIENG-3368)
* [RHOAIENG-3461](https://issues.redhat.com/browse/RHOAIENG-3461)
This PR fixes 2 issues:
* Adds a parameter to be able to configure a Git revision to checkout when fetching the model from the Git repository.
* Sets this parameter to the [pull request ref](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally?platform=linux#modifying-an-inactive-pull-request-locally) when the PR check in OpenShift CI is run to ensure the latest changes are tested.
Locally on an OpenShift cluster.
=> RHOAIENG-3368|RHOAIENG-3461- Include Git model repo revision param and use it in the PR check

test/shell-pipeline-tests/common.sh
Fix for #214.
Forgot to include the quotes, my bad. Without them, there is only 1 argument (`-n`) and the condition is [always true](https://www.gnu.org/software/bash/manual/bash.html#index-test):
```
1 argument
The expression is true if, and only if, the argument is not null.
```
=> RHOAIENG-3461 - Fix

pipelines/tekton/aiedge-e2e/templates/credentials-s3.secret.yaml.template
This PR adds instructions to the [credentials-s3.secret.template](https://github.com/opendatahub-io/ai-edge/blob/5960d4fc90c6f5aeb7c6a4eab5af5b1c2e972158/pipelines/tekton/aiedge-e2e/templates/credentials-s3.secret.yaml.template) about the optional endpoint_url and region params. [JIRA](https://issues.redhat.com/browse/RHOAIENG-437)
To fetch models from S3 in a different region from the IAM credentials, user can consider endpoint_url param as an optional one and pass the correct region to the credentials secret. This way region will take precedence over endpoint_url and allows the task to download model from the specified region.
=> RHOAIENG-437: Add instructions to fetch models from different s3 regions

pipelines/tekton/aiedge-e2e/tasks/retrieve-build-image-info.task.yaml
This PR stacks upon #215 as another preparatory commit for [RHOAIENG-1119](https://issues.redhat.com//browse/RHOAIENG-1119). It will be held until that one is merged, but it can still be reviewed, by just reviewing the new commit(s).
With this change, we now get info for the image from the image metadata using `skopeo inspect`, rather than from the ImageStream resource in OpenShift.
- `make go-test` runs successfully
- Example pipelineruns executed manually with success
=> RHOAIENG-1119: Don't rely on imagestream in image info task

pipelines/tekton/aiedge-e2e/aiedge-e2e.bike-rentals.pipelinerun.yaml, pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml, pipelines/tekton/aiedge-e2e/aiedge-e2e.tensorflow-housing.pipelinerun.yaml, pipelines/tekton/aiedge-e2e/tasks/retrieve-build-image-info.task.yaml
This PR stacks upon #215 and #217. It will be held until those are merged, but it can still be reviewed, by just reviewing the new commit(s). This PR is the main change for the [RHOAIENG-1119](https://issues.redhat.com//browse/RHOAIENG-1119).
This will allow overriding the internal image registry reference, and
use any other image registry, repo, and tag instead.
There's a default set for the new param to maintain the old behaviour,
and the same value is set in the example PipelineRun files by default.
- `make go-test` run successfully
- Example pipelines run manually using default value for new parameter, proving that existing behaviour works as expected.
- Example pipelines run, with the new parameter set to `quay.io/grdryn/$(params.model-name):$(params.model-version)-candidate`, …
=> RHOAIENG-1119: Add new candidate-image-tag-reference parameter

pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml, pipelines/tekton/aiedge-e2e/tasks/retrieve-build-image-info.task.yaml
~This PR stacks upon #215, #217, and #218. It will be held until those are merged, but it can still be reviewed, by just reviewing the new commit(s).~ This PR is an cleanup change to keep the result names meaningful.
JIRA: https://issues.redhat.com/browse/RHOAIENG-1119
The following result name changes are included in this change; because
the image is not necessarily internal any longer, and/or the
properties are not specific to the candidate image:
- `internal-registry-url` -> `candidate-image-tag-reference`
- `internal-image-url` -> `image-digest-reference`
- `internal-image-size` -> `image-size-bytes`
- `internal-image-created-at` -> `image-creation-time`
- Example PipelineRuns execute successfully
=> RHOAIENG-1119: Update result names that assume "internal" image

pipelines/README.md
Rework the Data for testing the model inferencing endpoint section to focus on the default example setups.
The original content has a very strong "You will need to create a ConfigMap ..." at the start and "prepared test data configmaps, which you can use" but when following the two example models (bike rentals and housing), nothing needs to be created or used explicitly -- `oc apply -k` takes care of everything. 
Not tested.
=> Rework the Data for testing the model inferencing endpoint section to focus on the default example setups.

pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml, pipelines/tekton/gitops-update-pipeline/test-mlflow-retrieve-image-info-task.yaml
Make the GitOps pipeline find the target registry URL again. This amends e3e731b7bc143e1bbaa3a8f3a5a58bf242631c38 and e1cfc6839c7ec44bd5f5e7e54c31cc8cd22276c5 and uses the `target-image-tag-references` to figure out the registry URL.
Also updating the `useMergedBuildTestPipeline` because that's what the repo seems to default to these days.
Manually.
=> Make the GitOps pipeline find the target registry URL again

acm/odh-edge/base/namespace.yaml, acm/registration/near-edge/base/near-edge.yaml, acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml, acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
JIRA: https://issues.redhat.com/browse/RHOAIENG-2787
This is a preparatory commit for [RHOAIENG-2787](https://issues.redhat.com//browse/RHOAIENG-2787), as not needing to use ACM Policy will make things a little easier for non-ACM cases.
This works as expected as long as the namespace is specified in the GitOps repo, and has the correct `argocd.argoproj.io/managed-by` label value.
We already had the namespace specified in the GitOps repo, but we didn't include the label.
More information on this label can be found here:
https://docs.openshift.com/gitops/1.11/argocd_instance/setting-up-argocd-instance.html
- Created both example applications through ACM successfully, and noticed that they were created as expected on the edge clusters
- Deleted both of the apps successfully on the ACM hub …
=> RHOAIENG-2787: Let ArgoCD create namespace, rather than using ACM Policy

acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml, acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml, acm/registration/near-edge/test/bike-rental-app/kustomization.yaml, acm/registration/near-edge/test/tensorflow-housing-app/kustomization.yaml
Follow-up to the #229 which contained some unused references to `Policy` and `PlacementBinding`. Unfortunately kustomize doesn't fail for test patch operation if a resource doesn't exist as can be seen in kubernetes-sigs/kustomize/issues/4379.
Ran kustomize before and after, there was no difference in the output, which means the removed parts were not applied.
=> Remove orphaned Policy and PlacementBinding references

Makefile, pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml, test/e2e-tests/README.md, test/e2e-tests/support/options.go, test/e2e-tests/support/tekton.go, test/e2e-tests/tests/pipelines_test.go
What this does:
- A self signed cert can be passed as a parameter to the MLops pipeline and can be used for use with private services throughout the pipeline, but for ones that only use git
- Documents the process and an optional step in the pipeline docs
- Use the e2e test provided in the repo
- Update the pipeline run to use a git repo that uses SSC (ping me for a repo and a cert to use!)
- Get access to that self signed cert and use it's path in the e2e tests as below
- Run 
```bash
make AWS_SECRET_ACCESS_KEY=... AWS_ACCESS_KEY_ID=... S3_REGION=... S3_ENDPOINT=... IMAGE_REGISTRY_USERNAME=...  IMAGE_REGISTRY_PASSWORD=... SELF_SIGNED_CERT=<PATH_TO_SSC> S3_BUCKET=... NAMESPACE=... TARGET_IMAGE_TAGS_JSON=... go-test-setup
```
- And then run 
```bash
make AWS_SECRET_ACCESS_KEY=... …
```
=> RHOAIENG-4166: Add support for self signed certs in the MLOps pipeline

Makefile, pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml, pipelines/tekton/aiedge-e2e/tasks/kserve-download-model.yaml, test/e2e-tests/README.md, test/e2e-tests/support/options.go, test/e2e-tests/tests/pipelines_test.go
Add support for using self signed certs with kserve to download models from an object store 
- Use the e2e test provided in the repo
- Setup e2e tests as normal
```bash
make AWS_SECRET_ACCESS_KEY=... AWS_ACCESS_KEY_ID=... S3_REGION=... S3_ENDPOINT=... IMAGE_REGISTRY_USERNAME=...  IMAGE_REGISTRY_PASSWORD=... S3_BUCKET=... NAMESPACE=... TARGET_IMAGE_TAGS_JSON=... go-test-setup
```
- Set the new env variable `S3_SELF_SIGNED_CERT` as the path to the cert
- And then run 
```bash
make AWS_SECRET_ACCESS_KEY=... AWS_ACCESS_KEY_ID=... S3_REGION=... S3_ENDPOINT=... IMAGE_REGISTRY_USERNAME=...  IMAGE_REGISTRY_PASSWORD=...  S3_BUCKET=... NAMESPACE=... TARGET_IMAGE_TAGS_JSON=... S3_SELF_SIGNED_CERT=... go-test
```
=> RHOAIENG-4873: Kserve self signed certs 

test/shell-pipeline-tests/common.sh
I found out that rehearsals run on the openshift/release repository PR set the value of the  `PULL_NUMBER` env variable of the job to the PR in the openshift/release repository. This naturally leads to a rehearsal job run failing because the pipeline is trying to fetch container files from the PR for ai-edge repository, which does not exist with that `PULL_NUMBER` (the PR exists just in the openshift/release repository). Therefore, for rehearsals we should always fetch the default, e.g. the main branch of the ai-edge repository, so the same approach we already use for nightly jobs.
Locally.
=> Don't use PR branch for rehearsals in the openshift/release repository

pipelines/containerfiles/Containerfile.openvino.mlserver.mlflow
Removes the `METRICS_PORT` argument from the openvino containerfile since it is not referenced anywhere in the build process and the openvino [metrics endpoint is served on the rest api port](https://docs.openvino.ai/2022.3/ovms_docs_metrics.html#enable-metrics) 
You can build this locally with any model format supported by openvino:
```bash
$ aws s3 cp --recursive s3://rhoai-edge/example-models/fraud-detection/ /tmp/fraud-detection
$ podman build --build-arg MODEL_NAME=fraud-detection -f pipelines/containerfiles/Containerfile.openvino.mlserver.mlflow --tag openvino-fraud-detection /tmp/fraud-detection/1/
$ podman run -d --rm -p 8080:8080 localhost/openvino-fraud-detection:latest
$ curl localhost:8080/metrics
ovms_requests_success{api="KServe",interface="REST",method="ModelReady",name="fra …
```
=> Remove METRICS_PORT container arg from openvino Containerfile

pipelines/tekton/aiedge-e2e/aiedge-e2e.bike-rentals.pipelinerun.yaml
`emptyDir` workspace named `workspace` is no longer needed as it was removed in https://github.com/opendatahub-io/ai-edge/commit/e1cfc6839c7ec44bd5f5e7e54c31cc8cd22276c5#diff-f322a0b0f23c8b879c98be3845b85e495e33da44e440b107f89b6a538c9861d4L380 but it was removed just from the `tensorflow-housing` pipeline run.
Locally & PR check
=> Remove emptyDir workspace from bike-rentals pipelinerun

Makefile, test/e2e-tests/README.md, test/e2e-tests/support/git.go, test/e2e-tests/support/options.go, test/e2e-tests/tests/pipelines_test.go
Adds support for testing the git ops pipeline with the go e2e test suite 
- Log into a cluster with `oc`
- Set the list of enviroment variables that are needed for running the tests for both the `go-test` and `go-test-setup` make targets. All of the required fields are listed [here](https://github.com/jackdelahunt/ai-edge/tree/git-ops-e2e-tests/test/e2e-tests) in the README
- Run `oc new-project {YOURNAMESPACE}`
- Run `make AWS_SECRET=... AWS_ACCESS=...  ... go-test-setup`
- Run `make S3_BUCKET=...  ... go-test`
- All tests should pass
=> RHOAIENG-4703: Add e2e-tests in Go to verify the GitOps pipeline is working correctly

manifests/pipelines/aiedge-e2e.pipeline.yaml, manifests/pipelines/gitops-update-pipeline.yaml, manifests/pipelines/s3-fetch-pipeline.yaml, manifests/tasks/check-model-and-containerfile-exists.yaml, manifests/tasks/kserve-download-model.yaml, pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-bike-rentals.yaml, pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-json.yaml, pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-tensorflow-housing.yaml
This removes 2 unused parameters:
* `current-namespace` from `check-model-and-containerfile-exists` and `kserve-download-model` tasks
* `model-name` from `gitops-update-pipeline`
PR check
=> Delete unused parameters from pipeline and tasks

pipelines/containerfiles/Containerfile.seldonio.mlserver.mlflow, pipelines/models/bike-rentals-auto-ml/conda.yaml, pipelines/models/bike-rentals-auto-ml/requirements.txt
`mlserver-flow` depends on `mlserver` without any version restrictions, so it pulls the latest one. [Yesterday, mlserver 2.15.0 was released](https://pypi.org/project/mlflow/2.15.0/#history) which is apparently not compatible with the rest in runtime, preventing model container to start. So I added the previous version 2.14.3, which worked fine, as a requirement.
PR check
=> Fix bike-rentals-auto-ml

manifests/pipelines/aiedge-e2e.pipeline.yaml, manifests/pipelines/s3-fetch-pipeline.yaml
**changes only applied to aiedge pipeline so far**
In the test stage of the aiedge-e2e pipeline, we deploy the built image by referring to it by the tag reference (rather than manifest digest reference), and we don't explicitly set the imagePullPolicy to Always. This can lead to difficult to a case where an older candidate image is already stored on the node from a previous run, and won't be refreshed before deploying. This could mean that the new image doesn't actually get tested.
- CI
- Run e2e tests as normal and all should pass
=> RHOAIENG-6634: Test stage can use wrong image, because of tag reference and imagePullPolicy

examples/tekton/aiedge-e2e/templates/credentials-git.secret.yaml.template, manifests/pipelines/git-fetch-pipeline.yaml, test/e2e-tests/README.md, test/e2e-tests/support/config.go, test/e2e-tests/support/setup.go, test/e2e-tests/support/tekton.go, test/e2e-tests/template.config.json, test/e2e-tests/tests/pipelines_test.go
**This is blocked by https://github.com/opendatahub-io/ai-edge/pull/284**
Users can now fetch from private repos, this pr adds that ability to the aiedge-e2e pipeline but once #284 is merged these changes will be moved there. And with that any docs that are needed to give users info on the new feature.
The e2e tests have beed updated to support this optional feature and have been passing when using the `git_fetch` test when cloning from my own private repo.
- Using e2e tests fill in `token` and `username` in `config.json`
- All tests should pass
I have a private example repo if needed for testing confirmation
=> RHOAIENG-371: Add pipeline support for git private repo using an authentication token

test/shell-pipeline-tests/seldon-bike-rentals/pipelines-test-seldon-bike-rentals.sh
Periodic job finishes with 190-194 tries out of 200 which means there is not enough room in case the environment is slower, leading to false negatives. Therefore, I am raising it to 220. Other pipelines are OK.
Not needed.
=> Increase timeout for the s3-fetch pipeline with bike-rentals

acm/odh-edge/apps/telemetry/otel-collector.yaml
Before this change, it would never get to a fully synced state in ArgoCD because it sees a diff between the live state versus the desired state of the manifest.
See screenshots above: it was tested by verifying that the issue no longer occurs after the change.
=> Fix ArgoCD sync of OTel collector

acm/odh-edge/apps/bike-rental-app/kustomization.yaml
It seems like the old manifest was deleted from quay.io. It probably didn't have a tag referring to it. This updates to the latest tagged image, and shouldn't get untagged.
I pointed my config to the source branch of this PR, and I can see that the image is rolled out successfully and is healthy:
=> Fix bike-rental-app image

manifests/pipelines/git-fetch-pipeline.yaml, manifests/pipelines/s3-fetch-pipeline.yaml, manifests/tasks/retrieve-build-image-info/README.md, manifests/tasks/retrieve-build-image-info/retrieve-build-image-info.yaml, test/e2e-tests/tests/pipelines_test.go
JIRA: [RHOAIENG-209](https://issues.redhat.com/browse/RHOAIENG-209)
Deprecating clustertasks and replacing with git-resolvers. The idea is we can currently pulling in pre-defined task yamls from the tekton catalog git repo. Ref: [Migration from clustertasks to tekton-resolvers ](https://www.redhat.com/en/blog/migration-from-clustertasks-to-tekton-resolvers-in-openshift-pipelines)
```
oc apply -k manifests/
oc create -f examples/tekton/aiedge-e2e/example-pipelineruns/git-fetch.tensorflow-housing.pipelinerun.yaml
```
=> RHOAIENG-209-Deprecate the use of Tekton ClusterTasks in any Pipelines
